services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123' 
      MYSQL_DATABASE: 'flask_crud'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
    ports:
      - "3307:3306" 
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql